<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dblp [
<!ELEMENT dblp (article|book)*>
<!ELEMENT article (author?)>
<!ELEMENT book (author?, title*)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
]>

<dblp>
  <article>
    <author>Mak Erot</author>
  </article>
  <book>
    <author>Kak Seto</author>
    <title>Pedo Lover</title>
  </book>
</dblp>
